const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');
const base=path.resolve(__dirname,'..');
function harness(initial={}){
 let root=structuredClone(initial), deliveries=[],faults=new Map();
 const at=p=>p? p.split('/').reduce((o,k)=>o?.[decodeURIComponent(k)],root):root;
 const write=(p,v)=>{if(!p){root=structuredClone(v);return;}const keys=p.split('/').map(decodeURIComponent);let o=root;for(const k of keys.slice(0,-1))o=o[k]??={};if(v===null)delete o[keys.at(-1)];else o[keys.at(-1)]=structuredClone(v);};
 const tag=p=>crypto.createHash('sha256').update(JSON.stringify(at(p)??null)).digest('hex');
 const context=vm.createContext({console:{log(){},warn(){},error(){}},TextEncoder,TextDecoder,URL,Response,Request,Headers,AbortSignal,crypto:crypto.webcrypto,atob,btoa,setTimeout,clearTimeout,Date,structuredClone,fetch:async(url,options={})=>{
  const u=new URL(url),p=u.pathname.replace(/^\//,'').replace(/\.json$/,'');const method=options.method||'GET';
  if(method==='PUT'&&options.headers['If-Match']!==tag(p))return new Response('',{status:412});
  if(method==='PUT')write(p,JSON.parse(options.body));
  if(method==='PATCH')for(const [key,value]of Object.entries(JSON.parse(options.body)))write(key,value);
  let value=structuredClone(at(p)??null);
  if(method==='GET'&&u.searchParams.has('shallow'))value=value?Object.fromEntries(Object.keys(value).map(k=>[k,true])):null;
  if(method==='GET'&&u.searchParams.has('orderBy')&&value){const field=JSON.parse(u.searchParams.get('orderBy'));let entries=Object.entries(value).filter(([,v])=>{
   const n=v?.[field]??null;if(u.searchParams.has('equalTo'))return n===JSON.parse(u.searchParams.get('equalTo'));
   return (!u.searchParams.has('startAt')||n>=Number(u.searchParams.get('startAt')))&&(!u.searchParams.has('endAt')||n<=Number(u.searchParams.get('endAt')));
  });entries.sort((a,b)=>(a[1]?.[field]||0)-(b[1]?.[field]||0));if(u.searchParams.has('limitToFirst'))entries=entries.slice(0,Number(u.searchParams.get('limitToFirst')));value=Object.fromEntries(entries);}
  return new Response(JSON.stringify(value),{status:200,headers:{ETag:tag(p)}});
 }});
 vm.runInContext(fs.readFileSync(path.join(base,'functions/subscription-config.js'),'utf8'),context);
 const source=fs.readFileSync(path.join(base,'push-worker/worker.js'),'utf8').replace(/^import .*;\n/,'').replace('export default {','globalThis.worker = {');vm.runInContext(source,context);
 context.sendTest=async(_env,sub,payload)=>{deliveries.push({sub:sub.id,payload:structuredClone(payload)});return faults.get(sub.id)||201;};
 vm.runInContext("accessToken=async()=> 'test-token';sendPush=sendTest;createFirebaseCustomToken=async(_env,uid)=>'token:'+uid;",context);
 const env={FIREBASE_DATABASE_URL:'https://db.test',PUSH_KV:{get:async()=>({})},ALLOWED_ORIGINS:'https://site.test',APP_URL:'https://site.test/kapani/',MAX_PUSH_PER_RUN:'10'};
 context.env=env;
 const call=(name,...args)=>context[name](env,...args);
 const request=async(route,body)=>{const response=await context.worker.fetch(new Request('https://worker.test'+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),env);return {status:response.status,data:await response.json()};};
 return {context,call,request,env,root:()=>root,deliveries,faults};
}
const ph='a'.repeat(64),users=()=>({A:{nick:'A',passwordHash:ph,balance:10000,accountVerified:true},B:{nick:'B',passwordHash:ph,balance:0,accountVerified:true},C:{nick:'C',passwordHash:ph,balance:0,job:'Доставщик',accountVerified:true}});
const sub=id=>({id,endpoint:'https://fcm.googleapis.com/'+id,keys:{p256dh:'test',auth:'test'},prefs:{enabled:true}});
const pending=job=>({...job,state:'pending',queuedAt:Date.now(),nextAttemptAt:Date.now(),attempts:0});
function notificationHarness(devices=[sub('pc')]){return harness({users:{...users(),B:{...users().B,notifications:{notice123:{text:'Hello',cat:'messages',createdAt:Date.now(),push:true}}}},pushDevices:{B:devices},pushOutbox:{job123:pending({type:'notification',id:'notice123',to:'B',sender:'A'})}});}
test('concurrent event and cron claim one job once',async()=>{const h=notificationHarness();await Promise.all([h.call('processJob','job123',{left:10}),h.call('processJob','job123',{left:10})]);assert.equal(h.deliveries.length,1);assert.equal(h.root().pushOutbox.job123.state,'sent');});
test('per-device budget continues same job without skipping devices',async()=>{const h=notificationHarness([sub('one'),sub('two'),sub('three')]);for(let i=0;i<3;i++)await h.call('processJob','job123',{left:1});assert.deepEqual(h.deliveries.map(x=>x.sub),['one','two','three']);assert.equal(h.root().pushOutbox.job123.state,'sent');});
test('temporary error retries only failed device',async()=>{const h=notificationHarness([sub('good'),sub('bad')]);h.faults.set('bad',503);await h.call('processJob','job123',{left:10});assert.equal(h.root().pushOutbox.job123.state,'retry');h.root().pushOutbox.job123.nextAttemptAt=1;h.faults.clear();await h.call('processJob','job123',{left:10});assert.deepEqual(h.deliveries.map(x=>x.sub),['good','bad','bad']);});
test('deleted notification cannot be recreated or pushed on replay',async()=>{const h=notificationHarness();await h.request('/notification/delete',{nick:'B',ph,notificationId:'notice123'});await h.call('processJob','job123',{left:10});assert.equal(h.deliveries.length,0);assert.equal(h.root().users.B.notifications.notice123,undefined);assert.ok(h.root().notificationTombstones.B.notice123);});
test('fanout preserves readAt and checks tombstones atomically',async()=>{const h=harness({users:users(),chat:{msg123:{nick:'A',text:'hello',createdAt:Date.now()}},notificationTombstones:{B:{chat_msg123:{deletedAt:1}}},pushDevices:{B:[sub('b')],C:[sub('c')]},pushOutbox:{chat_msg123:pending({type:'chat',id:'msg123',sender:'A'})}});await h.call('processJob','chat_msg123',{left:10});assert.equal(h.root().users.B.notifications?.chat_msg123,undefined);assert.equal(h.deliveries.length,1);assert.ok(h.root().users.C.notifications.chat_msg123);});
test('disabled category finishes without retry spam',async()=>{const s=sub('no');s.prefs.messages=false;const h=notificationHarness([s]);await h.call('processJob','job123',{left:10});assert.equal(h.deliveries.length,0);assert.equal(h.root().pushOutbox.job123.state,'skipped');});
test('410 removes obsolete endpoint, not other devices',async()=>{const h=notificationHarness([sub('old'),sub('new')]);h.faults.set('old',410);await h.call('processJob','job123',{left:10});assert.deepEqual(h.root().pushDevices.accounts.B.map(x=>x.id),['new']);});
test('retry is bounded and transitions to dead',async()=>{const h=notificationHarness();delete h.root().users.B.notifications.notice123;h.root().pushOutbox.job123.attempts=7;await h.call('processJob','job123',{left:10});assert.equal(h.root().pushOutbox.job123.state,'dead');});
test('expired processing lease is reclaimable; live lease is not',async()=>{const h=notificationHarness();Object.assign(h.root().pushOutbox.job123,{state:'processing',leaseUntil:Date.now()+60000});await h.call('processJob','job123',{left:10});assert.equal(h.deliveries.length,0);Object.assign(h.root().pushOutbox.job123,{leaseUntil:1,nextAttemptAt:1});await h.call('processJob','job123',{left:10});assert.equal(h.deliveries.length,1);});
test('cron migrates old queue and excludes terminal jobs',async()=>{const h=notificationHarness();h.root().pushOutbox.job123={type:'notification',id:'notice123',to:'B',sender:'A',queuedAt:Date.now()};h.root().pushOutbox.done123={state:'sent',nextAttemptAt:-1};await h.call('runCron');await h.call('runCron');assert.equal(h.deliveries.length,1);});
test('notify is idempotent and deletion remains final',async()=>{const h=harness({users:users(),pushDevices:{B:[sub('b')]}});const body={nick:'A',ph,targetNick:'B',notificationId:'event123',text:'hello'};assert.equal((await h.request('/notify',body)).status,200);await h.request('/notify',body);assert.equal(h.deliveries.length,1);await h.request('/notification/delete',{nick:'B',ph,notificationId:'event123'});await h.request('/notify',body);assert.equal(h.root().users.B.notifications.event123,undefined);assert.equal(h.deliveries.length,1);});
for(const [existing,gift,active,allowed] of [['none','plus',false,true],['none','ultra',false,true],['none','prime',false,true],['plus','ultra',true,true],['plus','prime',true,true],['ultra','prime',true,true],['plus','plus',true,true],['ultra','ultra',true,true],['prime','prime',true,true],['ultra','plus',true,false],['prime','ultra',true,false],['prime','plus',true,false],['ultra','plus',false,true],['prime','ultra',false,true],['prime','plus',false,true]])test(`gift ${existing}(${active?'active':'expired'}) -> ${gift}`,async()=>{
 const u=users();u.B.subscription=existing;u.B.subscriptionExpiry=new Date(Date.now()+(active?86400000:-86400000)).toISOString();const old=u.B.subscriptionExpiry;const h=harness({users:u,pushDevices:{}});const response=await h.request('/gift',{nick:'A',ph,recipientNick:'B',subscriptionType:gift,requestId:'request123'});assert.equal(response.status,allowed?200:400);assert.equal(h.root().users.A.balance,allowed?10000-({plus:299,ultra:899,prime:1499}[gift]):10000);if(allowed){assert.equal(h.root().users.B.subscription,gift);if(existing===gift&&active)assert.equal(new Date(h.root().users.B.subscriptionExpiry)-new Date(old),7*86400000);}
});
test('gift replay never charges twice',async()=>{const h=harness({users:users(),pushDevices:{}}),body={nick:'A',ph,recipientNick:'B',subscriptionType:'plus',requestId:'request123'};await h.request('/gift',body);await h.request('/gift',body);assert.equal(h.root().users.A.balance,9701);assert.equal(Object.keys(h.root().subscriptionGifts).length,1);});
test('concurrent gifts cannot overspend',async()=>{const u=users();u.A.balance=400;const h=harness({users:u,pushDevices:{}});await Promise.all(['request111','request222'].map(requestId=>h.request('/gift',{nick:'A',ph,recipientNick:'B',subscriptionType:'plus',requestId})));assert.equal(h.root().users.A.balance,101);assert.equal(Object.keys(h.root().subscriptionGifts).length,1);});
const pickup={lat:52.6,lng:38.4,address:'Продавец, дом 1'},dropoff={lat:52.61,lng:38.41,address:'Покупатель, дом 2'};
test('market listing missing or blank coordinates rejected server-side',async()=>{for(const point of [undefined,{lat:'',lng:'',address:'fake'},{lat:91,lng:1,address:'fake'}]){const h=harness({users:users()});const res=await h.request('/market/publish',{nick:'A',ph,listing:{id:'listing123',title:'Товар',price:100,pickupAddress:point}});assert.equal(res.status,400);assert.equal(h.root().marketplace,undefined);}});
test('business missing address rejected without fee charge',async()=>{const h=harness({users:users()});const res=await h.request('/business/apply',{nick:'A',ph,application:{id:'business123',name:'Test',desc:'Test',lat:'',lng:'',address:''}});assert.equal(res.status,400);assert.equal(h.root().users.A.balance,10000);});
test('market delivery purchase, shipping escrow, snapshots and payout are atomic',async()=>{
 const u=users();u.B.balance=5000;const h=harness({users:u,marketplace:{listing123:{id:'listing123',seller:'A',title:'Bike',price:1000,status:'active',category:'other',pickupAddress:pickup}},pushDevices:{}});
 const shipping=Math.round(h.context.distanceKm(pickup,dropoff)*200),body={nick:'B',ph,order:{id:'order123',source:'marketplace',listingId:'listing123',deliveryAddress:dropoff,deliveryPrice:shipping}};
 assert.equal((await h.request('/delivery/create',body)).status,200);
 assert.equal(h.root().users.A.balance,11000);assert.equal(h.root().users.B.balance,5000-1000-shipping);assert.equal(h.root().deliveryCustomOrders.order123.escrowAmount,shipping);
 h.root().marketplace.listing123.pickupAddress={lat:0,lng:0,address:'Changed'};assert.deepEqual(h.root().deliveryCustomOrders.order123.pickupAddress,pickup);
 for(const [nick,action]of [['C','take'],['C','start'],['C','complete'],['B','received'],['C','done'],['C','done']])assert.equal((await h.request('/delivery/action',{nick,ph,orderId:'order123',action})).status,200);
 assert.equal(h.root().users.C.balance,shipping);assert.equal(h.root().deliveryCustomOrders.order123.status,'done');
});
test('insufficient shipping funds rolls back listing sale and seller credit',async()=>{const u=users();u.B.balance=1000;const h=harness({users:u,marketplace:{listing123:{seller:'A',title:'Bike',price:1000,status:'active',pickupAddress:pickup}},pushDevices:{}});const shipping=Math.round(h.context.distanceKm(pickup,dropoff)*200);const res=await h.request('/delivery/create',{nick:'B',ph,order:{id:'order123',source:'marketplace',listingId:'listing123',deliveryAddress:dropoff,deliveryPrice:shipping}});assert.equal(res.status,409);assert.equal(h.root().users.A.balance,10000);assert.equal(h.root().marketplace.listing123.status,'active');assert.equal(h.root().users.B.balance,1000);});
test('wrong auth cannot delete another inbox or gift funds',async()=>{const h=notificationHarness();const r=await h.request('/notification/clear',{nick:'B',ph:'b'.repeat(64)});assert.equal(r.status,401);assert.ok(h.root().users.B.notifications.notice123);});
test('DM is derived from real source and sender, not a spoofed body',async()=>{const h=harness({users:users(),dms:{A__dm__B:{messages:{msg123:{nick:'A',text:'private',createdAt:Date.now()}}}},pushDevices:{B:[sub('b')]},pushOutbox:{dm_msg123:pending({type:'dm',id:'msg123',dmKey:'A__dm__B',sender:'A',to:'B'})}});await h.call('processJob','dm_msg123',{left:10});assert.equal(h.deliveries.length,1);assert.ok(h.root().users.B.notifications.dm_msg123.text.includes('private'));assert.ok(h.root().users.B.notifications.dm_msg123.url.includes('kpDm=A'));});
test('news creates one inbox per recipient and excludes author',async()=>{const h=harness({users:users(),news:{news123:{author:'A',title:'News',createdAt:Date.now()}},pushDevices:{B:[sub('b')]},pushOutbox:{news_news123:pending({type:'news',id:'news123',sender:'A'})}});await h.call('processJob','news_news123',{left:10});assert.equal(h.root().users.A.notifications,undefined);assert.ok(h.root().users.B.notifications.news_news123);assert.ok(h.root().users.C.notifications.news_news123);});
test('concurrent registration preserves both devices and concurrent preferences',async()=>{const h=harness({users:users(),pushDevices:{}});const bodies=['one','two'].map(id=>({nick:'B',ph,subscription:{endpoint:'https://fcm.googleapis.com/'+id,keys:{p256dh:'key',auth:'key'}},prefs:{enabled:true}}));const results=await Promise.all(bodies.map(x=>h.request('/subscribe',x)));assert.deepEqual(results.map(x=>x.status),[200,200]);assert.equal(h.root().pushDevices.accounts.B.length,2);await Promise.all(results.map(x=>h.request('/prefs',{nick:'B',ph,subscriptionId:x.data.subscriptionId,prefs:{enabled:true,news:false}})));assert.ok(h.root().pushDevices.accounts.B.every(s=>s.prefs.news===false));});
test('test endpoint creates inbox and durable job even with no device',async()=>{const h=harness({users:users(),pushDevices:{}});const r=await h.request('/test',{nick:'B',ph});assert.equal(r.status,200);assert.ok(r.data.notificationId);assert.ok(r.data.jobId);assert.equal(r.data.sent,0);assert.ok(h.root().users.B.notifications[r.data.notificationId]);assert.equal(h.root().pushOutbox[r.data.jobId].state,'skipped');});
test('server authentication verifies existing salted password without public hashes',async()=>{const u=users();u.A.passwordHashSalt='A';u.A.passwordHash=crypto.createHash('sha256').update('kapani::a::secret').digest('hex');const h=harness({users:u});assert.equal((await h.request('/auth',{name:'A',password:'badpassword'})).status,401);const r=await h.request('/auth',{name:'A',password:'secret'});assert.equal(r.status,200);assert.equal(r.data.user.nick,'A');const dir=await h.request('/directory',{nick:'A',ph:u.A.passwordHash});assert.equal(dir.data.users.B.passwordHash,undefined);});
test('address update changes listing but leaves existing order snapshot intact',async()=>{const h=harness({users:users(),marketplace:{listing123:{seller:'A',pickupAddress:pickup}},deliveryCustomOrders:{order123:{pickupAddress:pickup}}});assert.equal((await h.request('/market/address',{nick:'A',ph,listingId:'listing123',pickupAddress:dropoff})).status,200);assert.deepEqual(h.root().deliveryCustomOrders.order123.pickupAddress,pickup);assert.deepEqual(h.root().marketplace.listing123.pickupAddress,dropoff);assert.equal((await h.request('/market/address',{nick:'B',ph,listingId:'listing123',pickupAddress:pickup})).status,403);});
test('Web Push aes128gcm payload decrypts with recipient key (RFC8291)',async()=>{const h=harness(),receiver=crypto.createECDH('prime256v1');receiver.generateKeys();const auth=crypto.randomBytes(16);const subscription={keys:{p256dh:receiver.getPublicKey().toString('base64url'),auth:auth.toString('base64url')}};const encrypted=Buffer.from(await h.context.encryptPayload(subscription,'Kapani'));const salt=encrypted.subarray(0,16),keyLength=encrypted[20],sender=encrypted.subarray(21,21+keyLength),shared=receiver.computeSecret(sender);const ikm=Buffer.from(crypto.hkdfSync('sha256',shared,auth,Buffer.concat([Buffer.from('WebPush: info\0'),receiver.getPublicKey(),sender]),32));const key=Buffer.from(crypto.hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16));const nonce=Buffer.from(crypto.hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12));const ciphertext=encrypted.subarray(21+keyLength),decipher=crypto.createDecipheriv('aes-128-gcm',key,nonce);decipher.setAuthTag(ciphertext.subarray(-16));const clear=Buffer.concat([decipher.update(ciphertext.subarray(0,-16)),decipher.final()]);assert.equal(clear.subarray(0,-1).toString(),'Kapani');assert.equal(clear.at(-1),2);});
